### PR TITLE
ignore errors unloading OpenAL data. mitigates #178

### PR DESCRIPTION
**Pull request by coreyoconnor**
Not a real fix. Sufficient to avoid the issue for my play sessions tho. :)

### CODE REVIEW

**Comment by och-dx** [comment]
Can I use this fix without recompiling? Noob here.

**Comment by coreyoconnor** [comment]
No: This patch requires recompiling. What platform are you on?

Note to devs: Just noticed this has incorrect indentation. oops!

**Comment by och-dx** [comment]
> No: This patch requires recompiling. What platform are you on?
> 
> Note to devs: Just noticed this has incorrect indentation. oops!

Windows 10 pro 64 bit

**Comment by DanielGibson** [comment]
@coreyoconnor can you fix the indentation (and ideally amend the commit and force-push it), then I'll merge it

I can build new windows binaries that include this fix this weekend if no one beats me to it

**Comment by och-dx** [comment]
You guys are freaking awesome!

**Comment by och-dx** [comment]
Also, is it worth it to use updated version of OpenAL soft? Should I be using 32 or 64 bit library?

**Comment by coreyoconnor** [comment]
> @coreyoconnor can you fix the indentation (and ideally amend the commit and force-push it), then I'll merge it

done! let me know if I missed anything :)

**Comment by DanielGibson** [comment]
thanks!

**Comment by och-dx** [comment]
So does this mean you will upload a new version to the main site?

**Comment by DanielGibson** [comment]
I think I'll upload it here or in the issue (#178) first to find out if it actually fixes your problem.
But I won't get around to creating it before the weekend.

**Pull request merged**
