### PR TITLE
more fixes for VS 14

### PR DESCRIPTION
**Pull request by leffmann**
About the changes in codec.cpp: MSVC defines `HUGE_VAL` as `INFINITY`, while idMath does `#undef INFINITY`, presumably because it wants you to use its own `idMath::INFINITY` instead.

Feel free to pull and squash.

### CODE REVIEW

**Comment by DanielGibson** [comment]
I'll wait until everything builds before merging.

**Comment by DanielGibson** [comment]
replacing `abs()` with `idMath::Fabs()` may not yield the same behavior, afaik `abs()` implicitly casts to int first. not sure if that behavior actually was intended and if something breaks if it's changed

**Comment by leffmann** [comment]
You're right. The `std::abs`, if that's what is effectively being called, should be overloaded, but I'm not sure either what the real intention is.

Replacing HUGE_VAL with idMath::INFINITY should be fine given what the code does, and since it's defined not as infinity but as 1e30.

With the above commits everything builds, and seems to play fine, so feel free to pull if you think it looks OK.

**Comment by DanielGibson** [comment]
`std::abs()` has an overload for float, see http://www.cplusplus.com/reference/cmath/abs/

but I don't think that `std::abs()` was called - there's no `using namespace std;` in the code, so  `abs()` - should have called C's `abs()` (http://www.cplusplus.com/reference/cstdlib/abs/) which can't be overloaded, because C doesn't support function overloading.

**Comment by DanielGibson** [comment]
ok, arguing with standard behavior when talking about MSVC is kinda silly.
I just tested the following Code with MSVC6, MSVC2010 Express on WinXP and clang++ and g++ on Linux:
```
#include <cmath>
#include <cstdlib>
#include <cstdio>

int main()
{
	float f = -2.45f;
	float f2 = abs(f);
	printf("abs(%f) = %f\n", f, f2);
	return 0;
}
```

When built with MSV6 or (clan)g++ it prints `abs(-2.450000) = 2.000000`.
When built with MSVC2010 it prints `abs(-2.450000) = 2.450000`.

So somewhere between MSVC6 and 2010 these strange overloads for float were introduced, i.e. not just `float std::abs(float)` but also `float abs(float)` in the global namespace - WTF?!

Not sure what doom3 originally was built with - certainly not MSVC6, maybe 7.0 or 7.1 (2003)?

But either way, binaries of the code built with MSVC2010 or newer should have been sufficiently tested to assume that replacing `abs()` with `idMath::Fabs()` should be safe.

**Comment by DanielGibson** [comment]
merged (after removing the special casing for MSVC2015 with the _fileno() stuff)

**Comment by DanielGibson** [comment]
Thanks for the patches!

**Pull request closed without merging**
