### PR TITLE
Fix some warnings

### PR DESCRIPTION
**Pull request by turol**
I got tired of warnings and fixed some of the more spammy ones.

### CODE REVIEW

**Comment by HarrievG** [comment]
I have to say, that although with modern compilers, removing all the memcpy's to assignments does not give an performance decrease, on older platforms it might.. 

There are some things, like replacing memcpy with loops with assignments from which again it is difficult to say what the compiler will make if it. 

Most of this comes down to how intelligent the compiler is on bringing it back to an optimised form. 

Have you compared the assembly? 

Tbh, I have the same feeling as you, about the compiler warnings, but i am trained to be very diligent with potenional performance increases as the compiler is NOT god. Being verbose is some at places intentional. (Math classes most of the time) And sometimes you have to silence it with an compile flag, instead of rewriting the code..

That all being said, I think most of your changes are oké, but **I hope that someone with _more_ experience can look at this from an performance perspective and weed out the risky ones and ease the mind of the performance mongers**..

**Comment by turol** [comment]
No, I didn't inspect the assembly. I did benchmark it on a Raspberry Pi 4 just now though. No statistical difference in either load times (the save from #328) or timedemo performance on demo1.

**Comment by turol** [comment]
Rebased.

1.5.1 it out now, can this be merged?

**Comment by turol** [comment]
@DanielGibson ping

**Comment by DanielGibson** [comment]
oh right, sorry

**Pull request merged**
