### PR TITLE
Fix 'no specular' support

### PR DESCRIPTION
**Pull request by RalfVB**
Light entities can have the param 'nospecular' set, which skips the specular lighting.
However this never actually worked in Doom 3.
This fix addresses that.

Using IceColdDuke's PBR interaction shader (which exposes the problem clearly), this is without the fix: (nospecular is set on the laser, yet they are still generated, hence the strange lighting around the laser dot)
https://imgur.com/lIst0NA

With the fix applied (specular lights are properly skipped)
https://imgur.com/qO0m34V

### CODE REVIEW

**Comment by DanielGibson** [comment]
Somehow all the tabs used for indentation have been replaced with spaces, which makes it hard to tell what has actually changed in that function (vs what is just indented differently). It also makes the code look inconsistent in the editor and `git blame` will also be less useful for the affected code..

Can you try keeping the original indentation style?

**Comment by DanielGibson** [comment]
Also, doesn't this change the look of the original game?

**Comment by RalfVB** [comment]
Ahh, the tabs > spacing thing might be related to my text editor. 

Afaik it doesn't affect the base game at all. If they actually used nospecular anywhere, they were bound to notice it didn't work, right?

**Comment by DanielGibson** [comment]
There's 30 maps that contain `"nospecular" "1"`, 1043 occurrences.
I checked and it's indeed set at light entities.
All those lights will look different when this behavior is fixed..

**Comment by RalfVB** [comment]
Then dismiss the patch.

**Comment by DanielGibson** [comment]
Maybe there's a way to make sure it's only applied for new maps (where we can assume they have been tested with the fix applied and thus look as intended)?
Like a `"usenospecular" "1"`flag in the worldspawn?
Do you think that'd be useful for mappers/modders?

**Comment by RalfVB** [comment]
That could be a good solution, yes

**Comment by RalfVB** [comment]
A better approach might be to control it via a cvar?

**Comment by DanielGibson** [comment]
Why do you think that would be better?
I thought it would be best to let mappers specify that so the user doesn't have to change a cvar between playing old and new maps

**Comment by Arl90** [comment]
The idea of a worldpsawn flag is great. I would also add a cvar (disabled by default) to enable the correct behavior of this feature in the entire game.

**Comment by DanielGibson** [comment]
@Arl90 @EoceneMiacid Is anyone still interested in this? 

If so, see https://github.com/dhewm/dhewm3/pull/643
Please test that and provide a testmap, else I won't merge it!

**Pull request closed without merging**
